### ISSUE TITLE
Multiple CMMotionManager instances

### ISSUE THREAD

**Issue by paramaggarwal** [pwmckenna/react-native-motion-manager#6]
From [CMMotionManager docs](https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMMotionManager_Class/index.html):

> An app should create only a single instance of the CMMotionManager class. Multiple instances of this class can affect the rate at which data is received from the accelerometer and gyroscope.

Currently if both Accelerometer and Gyroscope were used, it would create two instances.

(Raised this to keep track of it, not asking for a fix - I do understand that it is the community's responsibility to help out.)

**Comment by pwmckenna** [comment]
@paramaggarwal thanks for the report. I don't really have much time to work on OSS at the moment, but I'll leave this open just to track. If anyone would like to take a crack at this, PRs welcome!
