### ISSUE TITLE
Naming collision

### ISSUE THREAD

**Issue by williambout** [pwmckenna/react-native-motion-manager#9]
`Error building DependencyGraph:
 Error: Naming collision detected: node_modules/react-native-motion-manager/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/polyfills/polyfills.js collides with node_modules/react-native/packager/react-packager/src/Resolver/polyfills/polyfills.js`

**Comment by bpolonia** [comment]
@williambout Have you been able to get this package to work?

@pwmckenna @brentvatne  Can you help us with this?

**Comment by williambout** [comment]
@bpolonia Yes, just delete the `react-native` folder in `node_modules/react-native-motion-manager/`

**Comment by pwmckenna** [comment]
Its entirely possible that the react peer dependency is out of date. Are you using npm 2? If so, it's probably installing your project's react-native dependency which is probably more recent than the peer dep defined here, so npm 2 goes ahead and installs another older copy for this module.

I'd be curious if this repros using npm 3. Regardless the peer dep for this package should be updated to include the newer versions of react-native once its been tested with them. I could use some help on that front.

**Comment by bpolonia** [comment]
@williambout That worked. Thanks!

**Comment by pwmckenna** [comment]
just published v0.0.6 which just allowed any version of the react-native dep. I'm going to hope for the best and close this for now, but let me know if anyone runs into trouble with this again.

**Comment by williambout** [comment]
Problem solved thanks @pwmckenna 👍
